#!/bin/bash
pwd
script that prints the absolute path name of thee current working directory

This is the script that prints the absolute path name of thee current working directory of this particular project, I already ensured that I gave an accurate during the scripting.

